# Generated by Django 5.0.1 on 2024-06-27 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_blog_heart_heart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creeated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default='default_profile.svg', null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
    ]
