# Generated by Django 5.0.1 on 2024-06-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_creeated_at_blog_created_at_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creeated_at',
            new_name='created_at',
        ),
    ]
